name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v3

      - uses: nrwl/nx-cloud-action@v2
        with:
          accessToken: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          agents: 3
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected -t lint test build --parallel

      - run: npx nx-cloud stop-all-agents
        if: always()
      - run: npx nx fix-ci
        if: always()
